DROP INDEX PK_HR_MEMBER;

DROP TABLE HR_MEMBER 
	CASCADE CONSTRAINTS;


CREATE TABLE HR_MEMBER (
	U_ID VARCHAR2(20) NOT NULL, 
	NAME VARCHAR2(50 CHAR) NOT NULL,
	PASSWD VARCHAR2(50 CHAR) NOT NULL,
	U_LEVEL NUMBER(1) DEFAULT 1,
	LOGIN NUMBER(7) DEFAULT 0,
	RECOMMEND NUMBER(7) DEFAULT 0,
	EMAIL VARCHAR2(320 BYTE),
	REG_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE HR_MEMBER IS '회원';

COMMENT ON COLUMN HR_MEMBER.U_ID IS '아이디';

COMMENT ON COLUMN HR_MEMBER.NAME IS '이름';

COMMENT ON COLUMN HR_MEMBER.PASSWD IS '비번';

COMMENT ON COLUMN HR_MEMBER.U_LEVEL IS '등급';

COMMENT ON COLUMN HR_MEMBER.LOGIN IS '로그인';

COMMENT ON COLUMN HR_MEMBER.RECOMMEND IS '추천';

COMMENT ON COLUMN HR_MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN HR_MEMBER.REG_DT IS '등록일';

CREATE UNIQUE INDEX PK_HR_MEMBER
	ON HR_MEMBER (
		U_ID ASC
	);

ALTER TABLE HR_MEMBER
	ADD
		CONSTRAINT PK_HR_MEMBER
		PRIMARY KEY (
			U_ID
		);